# nlp/Dockerfile
FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV NLP_PORT=8001

EXPOSE 8001

CMD ["sh", "-c", "python -m uvicorn app:app --host 0.0.0.0 --port $NLP_PORT"]